In [6]:
import torch

def pool_activations(acts: list[torch.Tensor]):
	results = []
	for j in range(len(acts[0])):
		col = [t[j] for t in acts]
		pooled = torch.vstack(col)
		results.append(pooled)
	return results

In [10]:
b = [[torch.ones((1, 2,2)), torch.ones((1, 5,2))], [torch.ones((1, 2,2)), torch.ones((1, 5,2))], [torch.ones((1, 2,2)), torch.ones((1, 5,2))] ]
b

[[tensor([[[1., 1.],
           [1., 1.]]]),
  tensor([[[1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.]]])],
 [tensor([[[1., 1.],
           [1., 1.]]]),
  tensor([[[1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.]]])],
 [tensor([[[1., 1.],
           [1., 1.]]]),
  tensor([[[1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.]]])]]

In [11]:
for i in pool_activations(b):
	print(i.shape)

torch.Size([3, 2, 2])
torch.Size([3, 5, 2])
